config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :spaceships
  resources :destinations
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, foreign_key: "user_id", class_name: "User"
  has_many :destinations
  validates :destination_id, presence: true
  validates :user_id, presence: true
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :spaceships
  has_many :bookings, through: :spaceships
  has_one_attached :photo

  def total
    destination.price * quantity
  end
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  # belongs_to :user
  has_many :bookings
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional fields in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings
    @destinations = Destination.all
    @spaceships = Spaceship.all
  end

  def bookings
    @bookingsall = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.price = @spaceships.price + @destinations.price
    @booking.user_id = current_user.id
    # @booking.spaceship_id = @spaceships.id
    # <li><%= @destination = Destination.find(params[:destination_id]) %></li>
    # @booking.destination_id = @destination.id
    # @booking.booking_price = @destination.price #review price calculation // no price in destination model
    if @booking.save
      redirect_to bookings_path(@booking)
    else
      redirect_to root_path
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking[:id])
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:departure_date, :return_date, :price, :pax, :payload, :destination_id)
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
    @destinations = Destination.all
  end

  def show
    @destination = Destination.find(params[:id])
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(destination_params)
    @destination.save!
    redirect_to destinations_path(@destination)
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])
    @destination.update(destination_params)
    redirect_to destination_path(@destination)
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    redirect_to destinations_path, status: :see_other
  end

  private

  def destination_params
    params.require(:destination).permit(:name, :distance, :price, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  def index
    @spaceships = Spaceship.all
  end

  def show
    @spaceship = Spaceship.find(params[:id])
    @booking = Booking.new
    @destinations = Destination.all
  end

  def new
    @spaceship = Spaceship.new
  end

  def create
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.availability = true
    @spaceship.save
    redirect_to spaceships_path(@spaceship)
  end

  def edit
    @spaceship = Spaceship.find(params[:id])
  end

  def update
    @spaceship = Spaceship.find(params[:id])
    @spaceship.update(spaceship_params)
    redirect_to spaceship_path(@spaceship)
  end

  def destroy
    @spaceship = Spaceship.find(params[:id])
    @spaceship.destroy
    redirect_to spaceships_path, status: :see_other
  end

  private

  def spaceship_params
    params.require(:spaceship).permit(:name, :payload, :pax, :availability, :price, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<header>
    <div class="header-banner">
      <div class="centered">Bookings</div>
    </div>
    <div class="clear"></div>

</header>

<div class="container">
  <div class="row mt-5 justify-content-md-left">
    <% @bookings.each do |booking| %>
      <div class="col-md-auto">
        <div class="card">
          <div class="card-body">
            <div class="col">
              <%# <%= cl_image_tag booking.photo.key, height: 300, width: 300, crop: :fill, class: "index-spaceship-image" unless spaceship.photo.key.nil? %>
            </div>

            <div class="col">
              <h3 class="card-title">Trip to: <%= booking.id %></h3>
              <p class="card-text">Price: <%= booking.price %></p>
              <p class="card-text">Departure Date: <%= booking.departure_date %></p>
              <p class="card-text">Return Date: <%= booking.return_date %></p>
              <p class="card-text">No. of Zozo: <%= booking.pax %></p>
              <p class="card-text">Cargaizon allowace: <%= booking.payload %></p>
              <p class="card-text text-muted">Last booked 3 minutes ago.</p>
              <br>
              <%= link_to "Book", booking_path(booking), class: "button-main" %>
              <br>
              <br>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <br>
  <div class="col">
  </div>
</div>

  <%= link_to "Make a booking", new_booking_path, class:"btn btn-primary" %>
  <%= link_to "Back to homepage", root_path, class:"btn btn-outline-dark"%>
</div>

app/views/bookings/new.html.erb
  # To review later if the form functions
<div class="mx-auto" style="width: 400px;" >
  <h2>Add a new booking</h2>
  <%= form_with model: @booking do |f| %>
    <%= f.label :departure_date %> <br>
    <%= f.number_field :departure_date %> <br>
    <%= f.label :return_date %> <br>
    <%= f.number_field :return_date %> <br>
    <%= f.submit %>
  <% end %>
  <%= link_to "Abort!", bookings_path(@booking)%>
  <%= link_to "Back to Destinations", destinations_path %>
</div>

app/views/destinations/edit.html.erb
<%= form_with model: @destination do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :distance %>
  <%= f.number_field :distance %>
  <%= f.submit %>
<% end %>

<%= link_to "Abort!", destinations_path(@destination)%>

app/views/destinations/index.html.erb
<header>
    <div class="header-banner">
    <div class="centered">Destinations</div>
    </div>
    <div class="clear"></div>

    </header>

<div class="container">
    <div class="row mt-5 justify-content-md-left">
    <% @destinations.each do |destination| %>
    <div class="col-md-auto">
      <div class="card">
        <div class="card-body">
          <div class="col">
    <%= cl_image_tag destination.photo.key, height: 300, width: 300, crop: :fill, class: "index-card-image" unless destination.photo.key.nil? %>

    </div>

    <div class="col">

      <h3 class="card-title"><%= destination.name %></h3>
      <p class="card-text">Distance: <%= destination.distance %></p>
      <p class="card-text">Price: <%= destination.price %></p>
      <p class="card-text text-muted">Last booked 5 minutes ago.</p>
      <br>


      <%= link_to "Info", destination_path(destination), class: "button-outline" %>
      <%= link_to "Choose Spaceship First", new_booking_path, class: "button-main" %>
      <br>
      <br>
        </div>
      </div>
    </div>
  </div>
    <% end %>
  </div>

  <br>
  <div class="col">
    <%= link_to "Back to homepage", root_path, class: "btn btn-dark" %>
    <%= link_to "Add a destination", new_destination_path, class: "btn btn-primary"%> <br>
  </div>
</div>

app/views/destinations/new.html.erb
<div class="mx-auto" style="width: 400px;" >
  <h2>Add new destination</h2>
  <%= form_with model: @destination do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :distance %>
    <%= f.number_field :distance, placeholder: "KM" %> <br>
    <%= f.label :price %>
    <%= f.number_field :price, placeholder: "$"%> <br>
    <%= f.label :photo %> <br>
    <%= f.file_field :photo, accept: 'image/png,image/jpeg' %> <br>
    <%= f.submit %>
  <% end %>
  <%= link_to "Abort!", destinations_path(@destination)%>
</div>

app/views/destinations/show.html.erb
<div class="container">
  <div class="card bg-light" style="width: auto;">
    <div class="row bg-dark card-row">
      <div class="col-6" style="width: 6;">
        <div class="row text-light">
          <div class="col-4">
            <h3><%= @destination.name %></h3>
              <p>Distance: </p>
              <p>Price: </p>
              <p>Description: </p>
          </div>
          <div class="col-8">
            <h3> Details </h3>
            <p><%= @destination.distance %></p>
            <p><%= @destination.price %></p>
            <p>Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet, consectetur, adipisci[ng] velit, sed quia non numquam [do] eius modi tempora inci[di]dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? </p>
          </div>
        </div>
        <div class="row bg-info text-center row-book-form">
          <h2>BOOK NOW!</h2>
          <div class="mx-auto book-form">
            <%= form_with model: @destination do |f| %>
              <h4> <%= current_user.first_name %>, enter your info.</h4>
              <div class= "booking-name">
                <div class="booking-first-name">
                  <%= f.label :first_name %>
                  <%= f.text_field :first_name, value: current_user.first_name %>
                </div>
                <div class="booking-last-name">
                  <%= f.label :last_name%>
                  <%= f.text_field :last_name, value: current_user.last_name %> <br>
                </div>
              </div>
              <div class= "booking-date">
                <div class="booking-date-departure">
                  <%= f.label :departure %>
                  <%= f.date_field :departure_date %> <br>
                </div>
                <div class="booking-date-return">
                  <%= f.label :return %>
                  <%= f.date_field :return_date %> <br>
                </div>
              </div>
              <%= f.label :pax %>
              <%= f.number_field :pax %> <br>
              <%= f.label :payload %>
              <%= f.number_field :payload, placeholder: "KG" %> <br>
              <%= f.label :destination %>
              <%= f.text_field :destination, value: @destination.name %> <br>
              <%= f.submit %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-6">
        <%= image_tag (@destination.photo), class: "style-image"%>
      </div>
    </div>
  </div>

  <%= link_to "Delete", destination_path(@destination), class: "btn btn-warning",

    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
  <%= link_to "Back", destinations_path(@destination), class: "btn btn-dark" %>
  <%= link_to "Edit", edit_destination_path(@destination), class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ATLAS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path("") %>
  </head>

  <div class="container">
    <body>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>

        <div class="container">
          <% if user_signed_in? %>
            <h2>Hi <%= current_user.first_name %>!</h2>
          <% end %>
        </div>

      <%= yield %>

    </body>
   </div>

  <div class="container">
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
      </div>
      <div class="footer-copyright">
        Made with <i class="fas fa-heart"></i> by LOKAL
      </div>
    </div>
  </div>
</html>

app/views/pages/about.html.erb
<h1>About us!</h1>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1826&q=80);">
</div>
<div class="centered">
  <p class="about">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eleifend rutrum tellus, ut ultrices est fermentum eget. Sed blandit dui vel quam tincidunt eleifend. Ut nec porta enim. Nunc feugiat tempus finibus. Maecenas molestie lectus sit amet sem luctus, sed consequat tortor auctor. Morbi vel ullamcorper ipsum. Suspendisse pharetra interdum orci, ut consectetur mauris commodo ac. Vivamus volutpat magna a leo egestas, sed molestie lectus malesuada. Nam ut tellus ex. Cras enim odio, maximus nec scelerisque at, viverra sit amet ex. Cras gravida leo vel magna elementum iaculis. Duis fermentum ornare efficitur.</p>
  <p class="about">Morbi fringilla tincidunt nulla id cursus. Vivamus varius leo vel tortor porta volutpat. Curabitur mollis odio turpis, dapibus rutrum erat feugiat id. Nulla placerat nisi consectetur, rhoncus est vel, fringilla elit. Aliquam lobortis turpis mi, vel faucibus enim tincidunt eu. Nam a ipsum finibus, fringilla justo non, rhoncus libero. Praesent ut tortor sit amet lorem viverra maximus sed sit amet libero. Vivamus aliquam erat ut nisi ultricies posuere.</p>
  </div>
  <a class="btn btn-gradient" href="http://127.0.0.1:3000/">Back to homepage</a>

</div>

app/views/pages/home.html.erb
<! -- banner -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dqjdq06qv/image/upload/v1675237893/background-image-atlas_hooexg.jpg);">
  <div class="container">
      <h1>Atlas</h1>
      <p>Your next takeoff is one click-away!</p>
      <a class="btn btn-flat" href="spaceships/new">Book now</a>
  </div>
</div>

<! -- cards -->

<div class="container">
  <div class="title"><br>
    <h4>Highlights</h4>
  </div><br>
  <div class="cards">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dqjdq06qv/image/upload/v1675260739/nasa-CpHNKNRwXps-unsplash_dgdto3.jpg)">
        <div>
        <%= link_to 'Spaceships', spaceships_path, :class => "btn btn-dark"%>
        </div>
      </div>

      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dqjdq06qv/image/upload/v1675260962/peakpx_pvyazi.jpg)">
      <div>
        <%= link_to 'Destinations', destinations_path, :class => "btn btn-dark"%>
        </div>
      </div>

      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dqjdq06qv/image/upload/v1675260758/ju-guan-D-jLxBtEwaA-unsplash_efx5nd.jpg)">
      <div>
        <%= link_to 'Bookings', bookings_path, :class => "btn btn-dark"%>
        </div>
    </div>
</div>

<! --reviews -->
<br>
<br>

<div class="container">
<div class="title">
<h4>Reviews</h4>
<br>
<div class="review">
  <img src='https://res.cloudinary.com/dqjdq06qv/image/upload/v1675513132/Neil_Armstrong_gdgjqs.png' class="avatar-large" />
  <div class="review-content">
    <p><small>Neil Armstrong</small></p>
    <p>Outstanding service. I have been on Mars five times already.</p>
  </div>

<br>
<br>


<div class="review">
  <img src='https://res.cloudinary.com/dqjdq06qv/image/upload/v1675513099/thomas_pesquet_lzayzk.jpg' class="avatar-large"/>
  <div class="review-content">
    <p><small>Thomas Pesquet</small></p>
    <p>L'espace me manque quand je suis sur terre. Une expérience à couper le souffle.</p>
  </div>

</div>
</div>

app/views/pages/landing.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ATLAS - Coming Soon</title>
  <link rel="stylesheet" href="style.css" type="text/css">
</head>
<body>
  <div class="container">
    <img src="images/logo.png" class="logo" alt="">
    <div class="content">
      <p>Website is Under Construction</p>
      <h1>We're <span>Launching</span> Soon</h1>
      <div class="launch-time">
        <div>
          <p id="days">00</p>
          <span>Days</span>
        </div>
        <div>
          <p id="hours">00</p>
          <span>Hours</span>
        </div>
        <div>
          <p id="minutes">00</p>
          <span>Minutes</span>
        </div>
        <div>
          <p id="seconds">00</p>
          <span>Seconds</span>
        </div>
      </div>
      <button type="button">Learn More <img src="images/triangle.png"></button>
    </div>
    <img src="images/rocket.png" class="rocket">
  </div>

  <script>
    var countDownDate = new Date("Feb 4, 2023 00:00:00").getTime();
    var x = setInterval(function(){
      var now = new Date().getTime();
      var distance = countDownDate - now;

      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);

      document.getElementById("days").innerHTML = days;
      document.getElementById("hours").innerHTML = hours;
      document.getElementById("minutes").innerHTML = minutes;
      document.getElementById("seconds").innerHTML = seconds;

      if (distanc < 0) {
        clearInterval(x);
        document.getElementById("days").innerHTML = "00";
        document.getElementById("hours").innerHTML = "00";
        document.getElementById("minutes").innerHTML = "00";
        document.getElementById("seconds").innerHTML = "00";
      }
    },1000)
  </script>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dqjdq06qv/image/upload/v1675237893/logo_k1tjss.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Spaceships", spaceships_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Destinations", destinations_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Bookings", bookings_path, class: "nav-link" %>
            </li>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              </form>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "me.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Sign Up", new_user_registration_path , class: "dropdown-item" %>
                <%= link_to "Sign In", new_user_session_path , class: "dropdown-item" %>
                <%= link_to "My Bookings", bookings_path , class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/spaceships/edit.html.erb
<%= form_with model: @spaceship do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :payload %>
  <%= f.number_field :payload %>
  <%= f.label :pax %>
  <%= f.number_field :pax %>
  <%= f.label :availability %>
  <%= f.text_field :availability %>
  <%= f.submit %>
<% end %>

<%= link_to "Abort!", spaceships_path(@spaceship)%>

app/views/spaceships/index.html.erb
<header>
    <div class="header-banner">
    <div class="centered">Spaceships</div>
    </div>
    <div class="clear"></div>

</header>

<div class="container">
    <div class="row mt-5 justify-content-md-left">
    <% @spaceships.each do |spaceship| %>
    <div class="col-md-auto">
      <div class="card">
        <div class="card-body">
          <div class="col">
    <%= cl_image_tag spaceship.photo.key, height: 300, width: 300, crop: :fill, class: "index-spaceship-image" unless spaceship.photo.key.nil? %>
    </div>


    <div class="col">

      <h3 class="card-title"><%= spaceship.name %></h3>
      <p class="card-text">Max Payload: <%= spaceship.payload %></p>
      <p class="card-text">Passenger Capacity: <%= spaceship.pax %></p>
      <p class="card-text">Price: <%= spaceship.price %></p>
      <p class="card-text">Description: <%= spaceship.description %></p>
      <p class="card-text text-muted">Last booked 3 minutes ago.</p>
      <br>

      <%= link_to "Info", spaceship_path(spaceship), class: "button-main" %>
      <br>
      <br>
        </div>
      </div>
    </div>
  </div>
    <% end %>
  </div>

  <br>
  <div class="col">
    <%= link_to "Back to homepage", root_path, class: "btn btn-dark" %>
    <%= link_to "Add a spaceship", new_spaceship_path, class: "btn btn-primary"%> <br>
  </div>
</div>

app/views/spaceships/new.html.erb
<h2>Create new spaceship</h2>

<%# <form class="form-horizontal center" role="form"> %>
<%= form_with model: @spaceship do |f| %>
  <div class="field">
    <%= f.label :name, class: "col-md-4 control-label" %> <br>
    <%= f.text_field :name %> <br>
    <%= f.label :payload, class: "col-md-4 control-label" %> <br>
    <%= f.number_field :payload %> <br>
    <%= f.label :passenger_capacity, class: "col-md-4 control-label" %> <br>
    <%= f.number_field :pax %> <br>
    <%= f.label :price, class: "col-md-4 control-label" %> <br>
    <%= f.number_field :price %> <br>
    <%= f.label :description, class: "col-md-4 control-label" %> <br>
    <%= f.text_field :description %> <br>
    <%= f.label :photo %> <br>
    <%= f.file_field :photo, accept: 'image/png,image/jpeg' %> <br>
    <%= f.submit %>
  </div>

<% end %>

<br>
<%= link_to "Abort!", spaceships_path(@spaceship)%>

app/views/spaceships/show.html.erb
<div class="container">
  <div class="card bg-light">
    <div class="card-row-spaceship">
        <div class="row d-flex">
          <div class="col">
            <h3><strong><%= @spaceship.name %></strong></h3>
              <p>Max Payload: <%= @spaceship.payload %></p>
              <p>Passengers: <%= @spaceship.pax %></p>
              <p>Availability:<%= @spaceship.availability %> </p>
              <p>Description: Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit,
              sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, </p>
        </div>

        <div class="row row-book-form">
        <br><br><br>
          <h3><strong>Make your booking</strong></h3>
          <div class="col-md-6 book-form">
            <%= form_with model: @booking do |f| %>
              <h4> <%= current_user.first_name %>, enter your info.</h4>
              <div class= "booking-name">
                <div class="booking-first-name">
                  <%= f.label :first_name%>
                  <%= f.text_field :first_name, value: current_user.first_name %>
                </div>
                <div class="booking-last-name">
                  <%= f.label :last_name%>
                  <%= f.text_field :last_name, value: current_user.last_name%> <br>
                </div>
              </div>
              <div class= "booking-date">
                <div class="booking-date-departure">
                  <%= f.label :departure %>
                  <%= f.date_field :departure_date %> <br>
                </div>
                <div class="booking-date-return">
                  <%= f.label :return %>
                  <%= f.date_field :return_date %> <br>
                </div>
              </div>
              <%= f.label :pax %>
              <%= f.number_field :pax %> <br>
              <%= f.label :payload %>
              <%= f.number_field :payload, placeholder: "KG" %> <br>
              <%= f.label :spaceship %>
              <%= f.text_field :spaceship, value: @spaceship.name %> <br>
              <% @booking.spaceship_id = @spaceship.id %>

              <label for="destination">Choose a destination:</label>
              <select name="destination" id="destination">
                <%= @destinations.each do |destination| %>
                  <option value="destination"><%= destination.name %></option>
                  <%= @booking.destination_id = destination.id %>
                <% end %>
              </select>



              <%= f.submit %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col">
        <%= image_tag (@spaceship.photo), height: 400, crop: :fill %>

      </div>
    </div>
</div>

  <br>

  <%= link_to "Delete", spaceship_path(@spaceship), class: "btn btn-warning",
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
  <%= link_to "Back", spaceships_path(@spaceship), class: "btn btn-dark"%>
  <%= link_to "Edit", edit_spaceship_path(@spaceship), class: "btn btn-primary"%>

</div>